<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('senior_programs', function (Blueprint $table) {
            $table->comment('');
            $table->increments('id');
            $table->unsignedInteger('senior_training_id')->index('senior_programs_senior_training_id_foreign')->comment('senior_trainings_id');
            $table->tinyInteger('disp_flag')->comment('表示フラグ');
            $table->integer('disporder')->comment('表示順');
            $table->string('preview_pass')->comment('プレビューパスワード');
            $table->string('name')->comment('科目');
            $table->string('kamoku')->comment('科目');
            $table->string('fixed_number')->comment('募集定員');
            $table->string('related_organization_num')->comment('連携機関病院数');
            $table->text('related_organization')->comment('連携機関病院名');
            $table->string('advising_doctors_num')->comment('指導医数');
            $table->string('supervisor')->comment('プログラム責任者');
            $table->text('supervisor_description')->comment('プログラム責任者経歴');
            $table->string('advising_doctors')->comment('指導医名・専門');
            $table->text('program_feature')->comment('研修の特徴');
            $table->text('program_contents1')->comment('研修の内容：研修期間を通じて行われる勉強会・カンファレンスなどの教育機会');
            $table->text('program_contents2')->comment('研修の内容：外来医療');
            $table->text('program_contents3')->comment('研修の内容：病棟医療');
            $table->text('program_contents31')->comment('研修の内容：在宅医療');
            $table->text('program_contents32')->comment('研修の内容：手術治療');
            $table->text('program_contents33')->comment('研修の内容：臨床研究');
            $table->text('program_contents4')->comment('研修の内容：その他');
            $table->text('selection_criteria')->comment('選考基準');
            $table->text('application_term')->comment('応募期間');
            $table->text('payment')->comment('給与');
            $table->text('social_insurance')->comment('社会保険');
            $table->boolean('mpli_flg')->comment('医師賠償責任保険有無');
            $table->string('mpli')->comment('医師賠償責任保険');
            $table->text('holidays')->comment('休日・休暇');
            $table->boolean('duty_flg')->comment('当直有無');
            $table->string('duty_month')->comment('当直月回数');
            $table->text('duty')->comment('当直');
            $table->boolean('housing_flg')->comment('住宅補助・寮有無');
            $table->text('housing')->comment('住宅補助・寮');
            $table->boolean('nursery_flg')->comment('院内保育／託児所有無');
            $table->string('nursery')->comment('院内保育／託児所');
            $table->boolean('overseas_education_flg')->comment('海外留学制度（後期時）有無');
            $table->text('overseas_education')->comment('海外留学制度');
            $table->boolean('returning_supports_flg')->comment('復職支援制度有無');
            $table->text('returning_supports')->comment('復職支援制度');
            $table->text('comment')->comment('備考');
            $table->string('url')->comment('病院URL');
            $table->string('tantou_dep')->comment('担当者部署');
            $table->string('tantou_title')->comment('担当者役職');
            $table->string('tantou_name')->comment('担当者名前');
            $table->string('tel')->comment('TEL');
            $table->string('dboard_dr_num')->comment('指導医数（ダッシュボード）');
            $table->string('dboard_residents_num')->comment('研修医数（ダッシュボード）');
            $table->string('dboard_monthly_income')->comment('月収（ダッシュボード）');
            $table->string('dboard_annual_income')->comment('年収（ダッシュボード）');
            $table->string('dboard_duty')->comment('月間当直数（ダッシュボード）');
            $table->string('dboard_fixed_number')->comment('定員（ダッシュボード）');
            $table->timestamps();
            $table->boolean('input_flg')->comment('入力完了');
            $table->text('resinavi_simple_dr_num')->nullable()->comment('早見表：指導医数');
            $table->text('resinavi_simple_residents_num')->nullable()->comment('早見表：在籍研修医数（2021年度時点）');
            $table->text('resinavi_simple_salary')->nullable()->comment('早見表：給与');
            $table->text('resinavi_simple_on_duty_num')->nullable()->comment('当直回数');
            $table->text('resinavi_simple_hosp_tour')->nullable()->comment('病院見学実施日');
            $table->text('resinavi_simple_hires_num')->nullable()->comment('採用予定人数');
            $table->text('resinavi_simple_exam_sche')->nullable()->comment('試験日程');
            $table->text('resinavi_department')->nullable()->comment('診療科');
            $table->text('resinavi_core_collabo_facility')->nullable()->comment('基幹施設／連携施設');
            $table->text('resinavi_collabo_facility')->nullable()->comment('連携施設');
            $table->text('resinavi_rotation_sche')->nullable()->comment('ローテーションスケジュール');
            $table->text('resinavi_case_num')->nullable()->comment('症例数');
            $table->text('resinavi_sub_specialty')->nullable()->comment('サブスペシャルティ');
            $table->text('resinavi_membership')->nullable()->comment('診療加盟');
            $table->text('resinavi_beds_num')->nullable()->comment('病床数');
            $table->text('resinavi_doctors_num')->nullable()->comment('医師数');
            $table->text('resinavi_instructors_num')->nullable()->comment('指導医数');
            $table->text('resinavi_outpatients')->nullable()->comment('平均外来患者数');
            $table->text('resinavi_inpatients')->nullable()->comment('平均入院患者数');
            $table->text('resinavi_features')->nullable()->comment('この研修プログラムの特徴');
            $table->text('resinavi_url')->nullable()->comment('URL');
            $table->text('resinavi_point')->nullable()->comment('ポイント');
            $table->string('remarks')->nullable();
            $table->text('resinavi_task_mon_1')->nullable()->comment('週間スケジュール月曜朝');
            $table->text('resinavi_task_mon_2')->nullable()->comment('週間スケジュール月曜午前');
            $table->text('resinavi_task_mon_3')->nullable()->comment('週間スケジュール月曜午後');
            $table->text('resinavi_task_mon_4')->nullable()->comment('週間スケジュール月曜夕方');
            $table->text('resinavi_task_tue_1')->nullable()->comment('週間スケジュール火曜朝');
            $table->text('resinavi_task_tue_2')->nullable()->comment('週間スケジュール火曜午前');
            $table->text('resinavi_task_tue_3')->nullable()->comment('週間スケジュール火曜午後');
            $table->text('resinavi_task_tue_4')->nullable()->comment('週間スケジュール火曜夕方');
            $table->text('resinavi_task_wed_1')->nullable()->comment('週間スケジュール水曜朝');
            $table->text('resinavi_task_wed_2')->nullable()->comment('週間スケジュール水曜午前');
            $table->text('resinavi_task_wed_3')->nullable()->comment('週間スケジュール水曜午後');
            $table->text('resinavi_task_wed_4')->nullable()->comment('週間スケジュール水曜夕方');
            $table->text('resinavi_task_thr_1')->nullable()->comment('週間スケジュール木曜朝');
            $table->text('resinavi_task_thr_2')->nullable()->comment('週間スケジュール木曜午前');
            $table->text('resinavi_task_thr_3')->nullable()->comment('週間スケジュール木曜午後');
            $table->text('resinavi_task_thr_4')->nullable()->comment('週間スケジュール木曜夕方');
            $table->text('resinavi_task_fri_1')->nullable()->comment('週間スケジュール金曜朝');
            $table->text('resinavi_task_fri_2')->nullable()->comment('週間スケジュール金曜午前');
            $table->text('resinavi_task_fri_3')->nullable()->comment('週間スケジュール金曜午後');
            $table->text('resinavi_task_fri_4')->nullable()->comment('週間スケジュール金曜夕方');
            $table->text('resinavi_task_sat_1')->nullable()->comment('週間スケジュール土曜朝');
            $table->text('resinavi_task_sat_2')->nullable()->comment('週間スケジュール土曜午前');
            $table->text('resinavi_task_sat_3')->nullable()->comment('週間スケジュール土曜午後');
            $table->text('resinavi_task_sat_4')->nullable()->comment('週間スケジュール土曜夕方');
            $table->text('resinavi_task_sun_1')->nullable()->comment('週間スケジュール日曜朝');
            $table->text('resinavi_task_sun_2')->nullable()->comment('週間スケジュール日曜午前');
            $table->text('resinavi_task_sun_3')->nullable()->comment('週間スケジュール日曜午後');
            $table->text('resinavi_task_sun_4')->nullable()->comment('週間スケジュール日曜夕方');
            $table->text('resinavi_responsible_per')->nullable()->comment('責任者');
            $table->text('resinavi_responsible_uni')->nullable()->comment('責任者の出身大学');
            $table->text('resinavi_depart_beds')->nullable()->comment('当科病床数');
            $table->text('resinavi_depart_doc')->nullable()->comment('当科医師数');
            $table->text('resinavi_depart_outpatients')->nullable()->comment('当科平均外来患者数');
            $table->text('resinavi_depart_inpatients')->nullable()->comment('当科平均入院患者数');
            $table->text('resinavi_enrolled_instructors')->nullable()->comment('在籍指導医（2021年度時点）');
            $table->text('resinavi_major_resident')->nullable()->comment('専攻医・後期研修医（2021年度時点）');
            $table->text('resinavi_conference')->nullable()->comment('カンファレンス');
            $table->text('resinavi_related_uni')->nullable()->comment('関連大学医局');
            $table->text('resinavi_salary')->nullable()->comment('給与');
            $table->text('resinavi_insurance')->nullable()->comment('医師賠償責任保険');
            $table->text('resinavi_hosing')->nullable()->comment('宿舎・住宅');
            $table->text('resinavi_social_insurance')->nullable()->comment('社会保険');
            $table->text('resinavi_academic_assist')->nullable()->comment('学会補助');
            $table->text('resinavi_on_duty_num')->nullable()->comment('当直回数');
            $table->text('resinavi_on_duty_fee')->nullable()->comment('当直科');
            $table->text('resinavi_holiday')->nullable()->comment('休日・有給');
            $table->text('resinavi_hospital_tour')->nullable()->comment('病院見学');
            $table->text('resinavi_exam_sche')->nullable()->comment('試験・採用');
            $table->text('resinavi_exam_num')->nullable()->comment('昨年度の受験者数');
            $table->text('resinavi_application_related')->nullable()->comment('応募関連');
            $table->text('resinavi_application_contact')->nullable()->comment('応募連絡先');
            $table->text('resinavi_program_name')->nullable()->comment('プログラム名');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('senior_programs');
    }
};
